<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE HT_2013-2020 [
<!ELEMENT Uniform_Crime_Report (report)>
<!ELEMENT Crime_Occured (DATA_YEAR, ORI, PUB_AGENCY_NAME, AGENCY_TYPE_NAME, STATE_ABBR, STATE_NAME, DIVISION_NAME,	COUNTY_NAME, REGION_NAME, POPULATION_GROUP_CODE)>
<!ELEMENT DATA_YEAR (#PCDATA)>
<!ELEMENT ORI (#PCDATA)>
<!ELEMENT PUB_AGENCY_UNIT (#PCDATA)>
<!ELEMENT AGENCY_TYPE_NAME (#PCDATA)>
<!ELEMENT STATE_ABBR (#PCDATA)>
<!ELEMENT STATE_NAME (#PCDATA)>
<!ELEMENT DIVISION_NAME (#PCDATA)>
<!ELEMENT COUNTY_NAME (#PCDATA)>
<!ELEMENT REGION_NAME (#PCDATA)>
<!ELEMENT POPULATION_GROUP_CODE (#PCDATA)>

<!ATTLIST Report row CDATA #REQUIRED>

]>


<HT_2013-2020>

	<report id = "row 1">
		<DATA_YEAR>2016</DATA_YEAR>
		<ORI>MO0480600</ORI>
		<PUB_AGENCY_NAME>Independence</PUB_AGENCY_NAME>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>	
		<STATE_ABBR>MO</STATE_ABBR>	
		<STATE_NAME>Missouri</STATE_NAME>
		<DIVISION_NAME>West North Central</DIVISION_NAME>
		<COUNTY_NAME>JACKSON</COUNTY_NAME>
		<REGION_NAME>Midwest</REGION_NAME>
		<POPULATION_GROUP_CODE>2</POPULATION_GROUP_CODE>

	</report>

	<report id = "row 2">
		<DATA_YEAR>2016</DATA_YEAR>
		<ORI>TX2201200</ORI>
		<PUB_AGENCY_NAME>Fort Worth</PUB_AGENCY_NAME>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>	
		<STATE_ABBR>TX</STATE_ABBR>	
		<STATE_NAME>Texas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<COUNTY_NAME>PARKER; DENTON; TARRANT</COUNTY_NAME>
		<REGION_NAME>South</REGION_NAME>
		<POPULATION_GROUP_CODE>1B</POPULATION_GROUP_CODE>

	</report>

	<report id = "row 3">
		<DATA_YEAR>2016</DATA_YEAR>
		<ORI>TX2270100</ORI>
		<PUB_AGENCY_NAME>Austin</PUB_AGENCY_NAME>
		<AGENCY_TYPE_NAME></AGENCY_TYPE_NAME>	
		<STATE_ABBR>TX</STATE_ABBR>	
		<STATE_NAME>Texas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<COUNTY_NAME>WILLIAMSON; TRAVIS</COUNTY_NAME>
		<REGION_NAME>South</REGION_NAME>
		<POPULATION_GROUP_CODE>1B</POPULATION_GROUP_CODE>

	</report>

	<report id = "row 4">
		<DATA_YEAR>2019</DATA_YEAR>
		<ORI>NV0020100</ORI>
		<PUB_AGENCY_NAME>Las Vegas Metropolitan Police Department</PUB_AGENCY_NAME>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>	
		<STATE_ABBR>NV</STATE_ABBR>	
		<STATE_NAME>Nevada</STATE_NAME>
		<DIVISION_NAME>Mountain</DIVISION_NAME>
		<COUNTY_NAME>CLARK</COUNTY_NAME>
		<REGION_NAME>West</REGION_NAME>
		<POPULATION_GROUP_CODE>1A</POPULATION_GROUP_CODE>

	</report>

	<report id = "row 5">
		<DATA_YEAR>2017</DATA_YEAR>
		<ORI>AZ0070500</ORI>
		<PUB_AGENCY_NAME>Chandler</PUB_AGENCY_NAME>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>	
		<STATE_ABBR>AZ</STATE_ABBR>	
		<STATE_NAME>Arizona</STATE_NAME>
		<DIVISION_NAME>Mountain</DIVISION_NAME>
		<COUNTY_NAME>MARICOPA</COUNTY_NAME>
		<REGION_NAME>West</REGION_NAME>
		<POPULATION_GROUP_CODE>2</POPULATION_GROUP_CODE>

	</report>

	<report id = "row 6">
		<DATA_YEAR>2018</DATA_YEAR>
		<ORI>ND0090200</ORI>
		<PUB_AGENCY_NAME>Fargo</PUB_AGENCY_NAME>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>	
		<STATE_ABBR>ND</STATE_ABBR>	
		<STATE_NAME>North Dakota</STATE_NAME>
		<DIVISION_NAME>West North Central</DIVISION_NAME>
		<COUNTY_NAME>CASS</COUNTY_NAME>
		<REGION_NAME>Midwest</REGION_NAME>
		<POPULATION_GROUP_CODE>2</POPULATION_GROUP_CODE>

	</report>

	<report id = "row 7">
		<DATA_YEAR>2020</DATA_YEAR>
		<ORI>GA0380100</ORI>
		<PUB_AGENCY_NAME>Newnan</PUB_AGENCY_NAME>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>	
		<STATE_ABBR>GA</STATE_ABBR>	
		<STATE_NAME>Georgia</STATE_NAME>
		<DIVISION_NAME>South Atlantic</DIVISION_NAME>
		<COUNTY_NAME>COWETA</COUNTY_NAME>
		<REGION_NAME>South</REGION_NAME>
		<POPULATION_GROUP_CODE>4</POPULATION_GROUP_CODE>

	</report>	

	<report id = "row 8">
		<DATA_YEAR>2020</DATA_YEAR>
		<ORI>GA0440200</ORI>
		<PUB_AGENCY_NAME>DeKalb County Police Department</PUB_AGENCY_NAME>
		<AGENCY_TYPE_NAME>County</AGENCY_TYPE_NAME>	
		<STATE_ABBR>GA</STATE_ABBR>	
		<STATE_NAME>Georgia</STATE_NAME>
		<DIVISION_NAME>South Atlantic</DIVISION_NAME>
		<COUNTY_NAME>DEKALB</COUNTY_NAME>
		<REGION_NAME>South</REGION_NAME>
		<POPULATION_GROUP_CODE>9A</POPULATION_GROUP_CODE>

	</report>

	<report id = "row 9">
		<DATA_YEAR>2020</DATA_YEAR>
		<ORI>GA0440200</ORI>
		<PUB_AGENCY_NAME>DeKalb County Police Department</PUB_AGENCY_NAME>
		<AGENCY_TYPE_NAME>County</AGENCY_TYPE_NAME>	
		<STATE_ABBR>GA</STATE_ABBR>	
		<STATE_NAME>Georgia</STATE_NAME>
		<DIVISION_NAME>South Atlantic</DIVISION_NAME>
		<COUNTY_NAME>DEKALB</COUNTY_NAME>
		<REGION_NAME>South</REGION_NAME>
		<POPULATION_GROUP_CODE>9A</POPULATION_GROUP_CODE>

	</report>

	<report id = "row 10">
		<DATA_YEAR>2020</DATA_YEAR>
		<ORI>GA0440200</ORI>
		<PUB_AGENCY_NAME>DeKalb County Police Department</PUB_AGENCY_NAME>
		<AGENCY_TYPE_NAME>County</AGENCY_TYPE_NAME>	
		<STATE_ABBR>GA</STATE_ABBR>	
		<STATE_NAME>Georgia</STATE_NAME>
		<DIVISION_NAME>South Atlantic</DIVISION_NAME>
		<COUNTY_NAME>DEKALB</COUNTY_NAME>
		<REGION_NAME>South</REGION_NAME>
		<POPULATION_GROUP_CODE>9A</POPULATION_GROUP_CODE>

	</report>	


</HT_2013-2020>